export enum CardType {
  ACTION = "isAction",
  ACTION_SUPPLIER = "isActionSupplier",
  ATTACK = "isAttack",
  BUY_SUPPLIER = "isBuySupplier",
  DRAWER = "isDrawer",
  DOOM = "isDoom",
  DURATION = "isDuration",
  FATE = "isFate",
  MULTI_DRAWER = "isMultiDrawer",
  NIGHT = "isNight",
  REACTION = "isReaction",
  RESERVE = "isReserve",
  GATHERING = "isGathering",
  TERMINAL = "isTerminal",
  ARTIFACT_SUPPLIER = "isArtifactSupplier",
  VILLAGE_SUPPLIER = "isVillageSupplier",
  TRASHING = "isTrashing",
  TRAVELLER = "isTraveller",
  TREASURE = "isTreasure",
  VICTORY = "isVictory",
}
