export enum SetId {
  ADVENTURES = "adventures",
  ALCHEMY = "alchemy",
  BASE_SET = "baseset",
  BASE_SET_2 = "baseset2",
  CORNUCOPIA = "cornucopia",
  DARK_AGES = "darkages",
  EMPIRES = "empires",
  GUILDS = "guilds",
  GUILDSCONUCOPIA = "guildscornucopia",
  HINTERLANDS = "hinterlands",
  INTRIGUE = "intrigue",
  INTRIGUE_2 = "intrigue2",
  NOCTURNE = "nocturne",
  PROMOS = "promos",
  PROSPERITY = "prosperity",
  RENAISSANCE = "renaissance",
  SEASIDE = "seaside",
}
