export const LOAD_INITIAL_KINGDOM = "LOAD_INITIAL_KINGDOM";
export const RANDOMIZE = "RANDOMIZE";
export const RANDOMIZE_FULL_KINGDOM = "RANDOMIZE_FULL_KINGDOM";
export const SELECT_CARD = "SELECT_CARD";
export const UNSELECT_CARD = "UNSELECT_CARD";
export const TOGGLE_CARD_SELECTION = "TOGGLE_CARD_SELECTION";