export const UPDATE_SETTINGS = "UPDATE_SETTINGS";
export const UPDATE_KINGDOM = "UPDATE_KINGDOM";
export const UPDATE_SELECTION = "UPDATE_SELECTION";
export const CLEAR_SELECTION = "CLEAR_SELECTION";
export const UPDATE_SPECIFYING_REPLACEMENT_SUPPLY_CARD = "UPDATE_SPECIFYING_REPLACEMENT_SUPPLY_CARD";
export const CLEAR_SPECIFYING_REPLACEMENT_SUPPLY_CARD = "CLEAR_SPECIFYING_REPLACEMENT_SUPPLY_CARD";