import type { IllustratorCard, YearOfSet } from "./digital-cards-type"

export const Year_set:YearOfSet[]=[
{ id: "baseset",                year: 2008, order:10 },
{ id: "promos",                 year: 2008, order:400 },
{ id: "baseset2",               year: 2016, order:12 },
{ id: "baseset2add",            year: 2016, order:13 },
{ id: "intrigue",               year: 2009, order:30 },
{ id: "intrigue2",              year: 2016, order:32},
{ id: "intrigue2add",           year: 2016, order:33 },
{ id: "seaside",                year: 2009, order:40 },
{ id: "alchemy",                year: 2010, order:50 },
{ id: "prosperity",             year: 2010, order:60 },
{ id: "cornucopia",             year: 2011, order:70 },
{ id: "hinterlands",            year: 2011, order:80},
{ id: "darkages",               year: 2012, order:90 },
{ id: "guilds",                 year: 2013, order:100 },
{ id: "guildscornucopia",       year: 2015, order:110 },
{ id: "adventures",             year: 2016, order:120 },
{ id: "empires",                year: 2016, order:130 },
{ id: "nocturne",               year: 2017, order:140 },
{ id: "renaissance",            year: 2018, order:150 },
{ id: "menagerie",              year: 2020, order:160 },
{ id: "allies",                 year: 2021, order:170 },
{ id: "plunder",                year: 2023, order:180 },
{ id: "risingsun",              year: 2024, order:190 },

{ id: "seaside2",               year: 2022, order:42 },
{ id: "seaside2add",            year: 2022, order:43 },
{ id: "prosperity2",            year: 2022, order:62 },
{ id: "prosperity2add",         year: 2022, order:63 },
{ id: "hinterlands2",           year: 2022, order:82 },
{ id: "hinterlands2add",        year: 2022, order:83 },
{ id: "guildscornucopia2",      year: 2023, order:112 },
{ id: "guildscornucopia2add",   year: 2023, order:113 },

{ id: "envoy",                  year: 2008, order:0 },
{ id: "blackmarket",            year: 2009, order:0 },
{ id: "stash",                  year: 2010, order:0 },
{ id: "walledvillage",          year: 2011, order:0 },
{ id: "governor",               year: 2011, order:0 },
{ id: "princeold",              year: 2014, order:0 },
{ id: "prince",                 year: 2022, order:0 },
{ id: "summon",                 year: 2015, order:0 },
{ id: "sauna",                  year: 2016, order:0 },
{ id: "avanto",                 year: 2016, order:0 },
{ id: "saunaavanto",            year: 2016, order:0 },
{ id: "dismantle",              year: 2017, order:0 },
{ id: "church",                 year: 2019, order:0 },
{ id: "captain",                year: 2019, order:0 },
{ id: "marchland",              year: 2024, order:0 },
];      

export const Cards_list_Illustrator:IllustratorCard[]= [

{ id:"adventurer", illustrator:"Ryan Laukat" },
{ id:"bureaucrat", illustrator:"Matthias Catrein" },
{ id:"cellar", illustrator:"Matthias Catrein" },
{ id:"chancellor", illustrator:"Matthias Catrein" },
{ id:"chapel", illustrator:"Matthias Catrein" },
{ id:"councilroom", illustrator:"Matthias Catrein" },
{ id:"feast", illustrator:"Matthias Catrein" },
{ id:"festival", illustrator:"Marcel-André Casasola Merkle" },
{ id:"gardens", illustrator:"Matthias Catrein" },
{ id:"laboratory", illustrator:"Julien Delval" },
{ id:"library", illustrator:"Harald Lieske" },
{ id:"market", illustrator:"Matthias Catrein" },
{ id:"militia", illustrator:"Matthias Catrein" },
{ id:"mine", illustrator:"Claus Stephan" },
{ id:"moat", illustrator:"Matthias Catrein" },
{ id:"moneylender", illustrator:"Matthias Catrein" },
{ id:"remodel", illustrator:"Matthias Catrein" },
{ id:"smithy", illustrator:"Matthias Catrein" },
{ id:"spy", illustrator:"Michael Menzel" },
{ id:"thief", illustrator:"Julien Delval" },
{ id:"throneroom", illustrator:"Harald Lieske" },
{ id:"village", illustrator:"Claus Stephan" },
{ id:"witch", illustrator:"Matthias Catrein" },
{ id:"woodcutter", illustrator:"Matthias Catrein" },
{ id:"workshop", illustrator:"Christof Tisch" },
{ id:"artisan", illustrator:"Harald Lieske" },
{ id:"copper", illustrator:"Ryan Laukat" },
{ id:"silver", illustrator:"Ryan Laukat" },
{ id:"gold", illustrator:"Ryan Laukat" },
{ id:"estate", illustrator:"Martin Hoffmann" },
{ id:"duchy", illustrator:"Martin Hoffmann" },
{ id:"province", illustrator:"Martin Hoffmann" },
{ id:"curse", illustrator:"Claus Stephan" },
{ id:"merchant", illustrator:"Joshua Stewart" },
{ id:"vassal", illustrator:"Julien Delval" },
{ id:"bandit", illustrator:"Julien Delval" },
{ id:"poacher", illustrator:"Joshua Stewart" },
{ id:"harbinger", illustrator:"Martin Hoffmann" },
{ id:"sentry", illustrator:"Eric J Carter" },







{ id:"alchemist", illustrator:"Simon Jannerland" },
{ id:"apothecary", illustrator:"Ryan Laukat" },
{ id:"apprentice", illustrator:"Martin Hoffmann" },
{ id:"familiar", illustrator:"Alex Drummond" },
{ id:"golem", illustrator:"Franz Vohwinkel" },
{ id:"herbalist", illustrator:"Harald Lieske" },
{ id:"philosophersstone", illustrator:"Jacob Corn" },
{ id:"possession", illustrator:"Kieron O'Gorman" },
{ id:"scryingpool", illustrator:"Klemens Franz" },
{ id:"transmute", illustrator:"Claus Stephan" },
{ id:"university", illustrator:"Marcel-André Casasola Merkle" },
{ id:"vineyard", illustrator:"Julien Delval" },
{ id:"potion", illustrator:"Claus Stephan" },

{ id:"ghostship", illustrator:"Matthias Catrein" },
{ id:"smugglers", illustrator:"RC Torres" },
{ id:"salvager", illustrator:"RC Torres" },
{ id:"haven", illustrator:"Claus Stephan" },
{ id:"ambassador", illustrator:"Alejandro Gutiérrez Franco" },
{ id:"seahag", illustrator:"Christof Tisch" },
{ id:"nativevillage", illustrator:"Franz Vohwinkel" },
{ id:"navigator", illustrator:"Maura Kalusky" },
{ id:"pirateship", illustrator:"Franz Vohwinkel" },
{ id:"merchantship", illustrator:"Ryan Laukat" },
{ id:"tactician", illustrator:"Martin Hoffmann" },
{ id:"fishingvillage", illustrator:"Harald Lieske" },
{ id:"island", illustrator:"Franz Vohwinkel" },
{ id:"wharf", illustrator:"Simon Jannerland" },
{ id:"bazaar", illustrator:"Martin Hoffmann" },
{ id:"treasuremap", illustrator:"Matthias Catrein" },
{ id:"explorer", illustrator:"Dennis Lohausen" },
{ id:"lookout", illustrator:"Alejandro Gutiérrez Franco" },
{ id:"treasury", illustrator:"Ryan Laukat" },
{ id:"cutpurse", illustrator:"Martin Hoffmann" },
{ id:"caravan", illustrator:"Marcel-André Casasola Merkle" },
{ id:"warehouse", illustrator:"Julien Delval" },
{ id:"lighthouse", illustrator:"Marcel-André Casasola Merkle" },
{ id:"pearldiver", illustrator:"Maura Kalusky" },
{ id:"embargo", illustrator:"Harald Lieske" },
{ id:"outpost", illustrator:"Claus Stephan" },
{ id:"harvest", illustrator:"Alayna Danner" },
{ id:"youngwitch", illustrator:"Jessi J" },
{ id:"horsetraders", illustrator:"Jeff Himmelman" },
{ id:"tournament", illustrator:"Taylor Bennett" },
{ id:"hamlet", illustrator:"Kurt Miller" },
{ id:"jester", illustrator:"Jeff Himmelman" },
{ id:"fortuneteller", illustrator:"Raven Mimura" },
{ id:"fairgrounds", illustrator:"Jessi J" },
{ id:"hornofplenty", illustrator:"Alayna Danner" },
{ id:"huntingparty", illustrator:"Kurt Miller" },
{ id:"menagerie", illustrator:"Matthew Tames" },
{ id:"farmingvillage", illustrator:"Garret DeChellis" },
{ id:"remake", illustrator:"Mark Poole" },
{ id:"trustysteed", illustrator:"Mark Poole" },
{ id:"followers", illustrator:"Lorraine Schleter" },
{ id:"princess", illustrator:"Lynell Ingram" },
{ id:"diadem", illustrator:"Ryan Laukat" },
{ id:"bagofgold", illustrator:"Ryan Laukat" },
{ id:"contraband", illustrator:"RC Torres" },
{ id:"peddler", illustrator:"Joshua Stewart" },
{ id:"bank", illustrator:"Jason Snair" },
{ id:"city", illustrator:"Marco Morte" },
{ id:"countinghouse", illustrator:"Matthias Catrein" },
{ id:"bishop", illustrator:"Rom" },
{ id:"grandmarket", illustrator:"Marcel-André Casasola Merkle" },
{ id:"goons", illustrator:"Tu Pei-Shu" },
{ id:"watchtower", illustrator:"Rick Hershey" },
{ id:"expand", illustrator:"Ryan Laukat" },
{ id:"kingscourt", illustrator:"Dennis Lohausen" },
{ id:"hoard", illustrator:"Colin Throm" },
{ id:"monument", illustrator:"Julien Delval" },
{ id:"forge", illustrator:"Martin Hoffmann" },
{ id:"rabble", illustrator:"RC Torres" },
{ id:"talisman", illustrator:"Eric J Carter" },
{ id:"mint", illustrator:"Kim Feigenbaum" },
{ id:"loan", illustrator:"Simon Jannerland" },
{ id:"traderoute", illustrator:"Harald Lieske" },
{ id:"quarry", illustrator:"Brian Brinlee" },
{ id:"royalseal", illustrator:"Jason Slavin" },
{ id:"mountebank", illustrator:"Kieron O'Gorman" },
{ id:"workersvillage", illustrator:"Claus Stephan" },
{ id:"vault", illustrator:"Alex Drummond" },
{ id:"venture", illustrator:"Lee Smith" },
{ id:"platinum", illustrator:"Ryan Laukat" },

{ id:"colony", illustrator:"Martin Hoffmann" },

{ id:"nobles", illustrator:"Marcel-André Casasola Merkle" },
{ id:"conspirator", illustrator:"Matthias Catrein" },
{ id:"miningvillage", illustrator:"Claus Stephan" },
{ id:"secretchamber", illustrator:"Marcel-André Casasola Merkle" },
{ id:"coppersmith", illustrator:"Claus Stephan" },
{ id:"pawn", illustrator:"Franz Vohwinkel" },
{ id:"courtyard", illustrator:"Harald Lieske" },
{ id:"tradingpost", illustrator:"Martin Hoffmann" },
{ id:"scout", illustrator:"Matthias Catrein" },
{ id:"duke", illustrator:"Christof Tisch" },
{ id:"baron", illustrator:"Ryan Laukat" },
{ id:"swindler", illustrator:"Alexander Jung" },
{ id:"bridge", illustrator:"Harald Lieske" },
{ id:"torturer", illustrator:"Franz Vohwinkel" },
{ id:"wishingwell", illustrator:"Ryan Laukat" },
{ id:"masquerade", illustrator:"Franz Vohwinkel" },
{ id:"ironworks", illustrator:"Martin Hoffmann" },
{ id:"steward", illustrator:"Matthias Catrein" },
{ id:"harem", illustrator:"Maura Kalusky" },
{ id:"minion", illustrator:"Christof Tisch" },
{ id:"saboteur", illustrator:"Dennis Lohausen" },
{ id:"upgrade", illustrator:"Matthias Catrein" },
{ id:"tribute", illustrator:"Matthias Catrein" },
{ id:"greathall", illustrator:"Julien Delval" },
{ id:"shantytown", illustrator:"Maura Kalusky" },







{ id:"lurker", illustrator:"Martin Hoffmann" },
{ id:"secretpassage", illustrator:"Marcel-André Casasola Merkle" },
{ id:"diplomat", illustrator:"Lorraine Schleter" },
{ id:"mill", illustrator:"Marcel-André Casasola Merkle" },
{ id:"courtier", illustrator:"Claus Stephan" },
{ id:"patrol", illustrator:"Harald Lieske" },
{ id:"replace", illustrator:"Claus Stephan" },







{ id:"advisor", illustrator:"Alayna Danner" },
{ id:"baker", illustrator:"Lynell Ingram" },
{ id:"butcher", illustrator:"Lynell Ingram" },
{ id:"candlestickmaker", illustrator:"Kelli Stakenas" },
{ id:"doctor", illustrator:"Lorraine Schleter" },
{ id:"herald", illustrator:"Jessi J" },
{ id:"journeyman", illustrator:"Kurt Miller" },
{ id:"masterpiece", illustrator:"Kelli Stakenas" },
{ id:"merchantguild", illustrator:"Eric J Carter" },
{ id:"plaza", illustrator:"Ryan Laukat" },
{ id:"soothsayer", illustrator:"Alayna Danner" },
{ id:"stonemason", illustrator:"Lorraine Schleter" },
{ id:"taxman", illustrator:"Jessi J" },
{ id:"bordervillage", illustrator:"Kurt Miller" },
{ id:"foolsgold", illustrator:"Ryan Laukat" },
{ id:"trader", illustrator:"Lorraine Schleter" },
{ id:"highway", illustrator:"Eric J Carter" },
{ id:"silkroad", illustrator:"Martin Hoffmann" },
{ id:"illgottengains", illustrator:"Jason Slavin" },
{ id:"embassy", illustrator:"Marco Morte" },
{ id:"nomadcamp", illustrator:"Garret DeChellis" },
{ id:"spicemerchant", illustrator:"Alayna Danner" },
{ id:"oracle", illustrator:"Jessi J" },
{ id:"cartographer", illustrator:"Mark Poole" },
{ id:"farmland", illustrator:"Eric J Carter" },
{ id:"noblebrigand", illustrator:"Joshua Stewart" },
{ id:"margrave", illustrator:"Joshua Stewart" },
{ id:"haggler", illustrator:"Claus Stephan" },
{ id:"scheme", illustrator:"Julien Delval" },
{ id:"inn", illustrator:"Marcel-André Casasola Merkle" },
{ id:"tunnel", illustrator:"Brian Brinlee" },
{ id:"crossroads", illustrator:"Matthias Catrein" },
{ id:"develop", illustrator:"Marco Morte" },
{ id:"oasis", illustrator:"Alayna Danner" },
{ id:"mandarin", illustrator:"Lynell Ingram" },
{ id:"cache", illustrator:"RC Torres" },
{ id:"duchess", illustrator:"Alayna Danner" },
{ id:"stables", illustrator:"Dennis Lohausen" },
{ id:"jackofalltrades", illustrator:"Kieron O'Gorman" },
{ id:"armory", illustrator:"Marcel-André Casasola Merkle" },
{ id:"vagrant", illustrator:"Joshua Stewart" },
{ id:"catacombs", illustrator:"Marcel-André Casasola Merkle" },
{ id:"count", illustrator:"Dennis Lohausen" },
{ id:"fortress", illustrator:"Marco Morte" },
{ id:"scavenger", illustrator:"Franz Vohwinkel" },
{ id:"marketsquare", illustrator:"Lorraine Schleter" },
{ id:"urchin", illustrator:"Martin Hoffmann" },
{ id:"rats", illustrator:"Ian Kirkpatrick" },
{ id:"sage", illustrator:"Harald Lieske" },
{ id:"forager", illustrator:"Eric J Carter" },
{ id:"altar", illustrator:"Matthias Catrein" },
{ id:"procession", illustrator:"Alex Drummond" },
{ id:"squire", illustrator:"Harald Lieske" },
{ id:"beggar", illustrator:"Garret DeChellis" },
{ id:"poorhouse", illustrator:"Jessi J" },
{ id:"deathcart", illustrator:"Marco Morte" },
{ id:"wanderingminstrel", illustrator:"Guillaume Ducos" },
{ id:"ironmonger", illustrator:"Dennis Lohausen" },
{ id:"hermit", illustrator:"Claus Stephan" },
{ id:"pillage", illustrator:"Claus Stephan" },
{ id:"mystic", illustrator:"Alayna Danner" },
{ id:"storeroom", illustrator:"Alex Drummond" },
{ id:"huntinggrounds", illustrator:"Simon Jannerland" },
{ id:"graverobber", illustrator:"Julien Delval" },
{ id:"counterfeit", illustrator:"Ryan Laukat" },
{ id:"cultist", illustrator:"Jason Slavin" },
{ id:"rogue", illustrator:"Jesse Mead" },
{ id:"marauder", illustrator:"Franz Vohwinkel" },
{ id:"bandofmisfits", illustrator:"RC Torres" },
{ id:"junkdealer", illustrator:"Kurt Miller" },
{ id:"feodum", illustrator:"Matthias Catrein" },
{ id:"rebuild", illustrator:"Kurt Miller" },
{ id:"banditcamp", illustrator:"RC Torres" },
{ id:"spoils", illustrator:"Ryan Laukat" },
{ id:"abandonedmine", illustrator:"Claus Stephan" },
{ id:"ruinedlibrary", illustrator:"Harald Lieske" },
{ id:"ruinedmarket", illustrator:"Marcel-André Casasola Merkle" },
{ id:"ruinedvillage", illustrator:"Doris Matthäus" },
{ id:"survivors", illustrator:"Alex Drummond" },
{ id:"madman", illustrator:"Claus Stephan" },
{ id:"mercenary", illustrator:"Martin Hoffmann" },
{ id:"hovel", illustrator:"Eric J Carter" },
{ id:"necropolis", illustrator:"Brian Brinlee" },
{ id:"overgrownestate", illustrator:"Martin Hoffmann" },
{ id:"knights", illustrator:"Matthias Catrein" },
{ id:"dameanna", illustrator:"Lorraine Schleter" },
{ id:"damejosephine", illustrator:"Lynell Ingram" },
{ id:"damemolly", illustrator:"Lynell Ingram" },
{ id:"damenatalie", illustrator:"Alayna Danner" },
{ id:"damesylvia", illustrator:"Jessi J" },
{ id:"sirbailey", illustrator:"Joshua Stewart" },
{ id:"sirdestry", illustrator:"Marco Morte" },
{ id:"sirmartin", illustrator:"Julien Delval" },
{ id:"sirmichael", illustrator:"Marco Morte" },
{ id:"sirvander", illustrator:"Garret DeChellis" },
{ id:"amulet", illustrator:"Matthias Catrein" },
{ id:"artificer", illustrator:"Lynell Ingram" },
{ id:"bridgetroll", illustrator:"Kurt Miller" },
{ id:"caravanguard", illustrator:"Julien Delval" },
{ id:"distantlands", illustrator:"Matthias Catrein" },
{ id:"dungeon", illustrator:"Martin Hoffmann" },
{ id:"duplicate", illustrator:"Ryan Laukat" },
{ id:"gear", illustrator:"Marco Morte" },
{ id:"giant", illustrator:"Marco Morte" },
{ id:"guide", illustrator:"Eric J Carter" },
{ id:"hauntedwoods", illustrator:"Kurt Miller" },
{ id:"hireling", illustrator:"Claus Stephan" },
{ id:"lostcity", illustrator:"Julien Delval" },
{ id:"magpie", illustrator:"Marco Morte" },
{ id:"messenger", illustrator:"Martin Hoffmann" },
{ id:"miser", illustrator:"Marco Morte" },
{ id:"page", illustrator:"Alayna Danner" },
{ id:"peasant", illustrator:"Harald Lieske" },
{ id:"port", illustrator:"Mark Poole" },
{ id:"ranger", illustrator:"Claus Stephan" },
{ id:"ratcatcher", illustrator:"Eric J Carter" },
{ id:"raze", illustrator:"RC Torres" },
{ id:"relic", illustrator:"Ryan Laukat" },
{ id:"royalcarriage", illustrator:"Kelli Stakenas" },
{ id:"storyteller", illustrator:"Claus Stephan" },
{ id:"swamphag", illustrator:"Jessi J" },
{ id:"transmogrify", illustrator:"Marco Morte" },
{ id:"treasuretrove", illustrator:"Marco Morte" },
{ id:"winemerchant", illustrator:"Eric J Carter" },
{ id:"coinoftherealm", illustrator:"Ryan Laukat" },
{ id:"alms", illustrator:"Matthias Catrein" },
{ id:"ball", illustrator:"Brian Brinlee" },
{ id:"bonfire", illustrator:"Brian Brinlee" },
{ id:"borrow", illustrator:"Lynell Ingram" },
{ id:"expedition", illustrator:"Joshua Stewart" },
{ id:"ferry", illustrator:"Mark Poole" },
{ id:"inheritance", illustrator:"Mark Poole" },
{ id:"lostarts", illustrator:"Joshua Stewart" },
{ id:"mission", illustrator:"Martin Hoffmann" },
{ id:"pathfinding", illustrator:"Garret DeChellis" },
{ id:"pilgrimage", illustrator:"Garret DeChellis" },
{ id:"plan", illustrator:"Jessi J" },
{ id:"quest", illustrator:"Jesse Mead" },
{ id:"raid", illustrator:"Jesse Mead" },
{ id:"save", illustrator:"Jessi J" },
{ id:"scoutingparty", illustrator:"Joshua Stewart" },
{ id:"seaway", illustrator:"Julien Delval" },
{ id:"travellingfair", illustrator:"Julien Delval" },
{ id:"trade", illustrator:"Marco Morte" },
{ id:"training", illustrator:"Jesse Mead" },
{ id:"treasurehunter", illustrator:"Alayna Danner" },
{ id:"warrior", illustrator:"Alayna Danner" },
{ id:"hero", illustrator:"Alayna Danner" },
{ id:"champion", illustrator:"Alayna Danner" },
{ id:"soldier", illustrator:"Harald Lieske" },
{ id:"fugitive", illustrator:"Harald Lieske" },
{ id:"disciple", illustrator:"Harald Lieske" },
{ id:"teacher", illustrator:"Harald Lieske" },
{ id:"engineer", illustrator:"Elisa Cella" },
{ id:"cityquarter", illustrator:"Matthias Catrein" },
{ id:"overlord", illustrator:"Elisa Cella" },
{ id:"royalblacksmith", illustrator:"Alayna Danner" },
{ id:"encampmentplunder", illustrator:"Jessi J" },
{ id:"encampment", illustrator:"Jessi J" },
{ id:"plunder", illustrator:"Franz Vohwinkel" },
{ id:"patricianemporium", illustrator:"Garret DeChellis" },
{ id:"patrician", illustrator:"Garret DeChellis" },
{ id:"emporium", illustrator:"Garret DeChellis" },
{ id:"settlersbustlingvillage", illustrator:"Jessi J" },
{ id:"settlers", illustrator:"Jessi J" },
{ id:"bustlingvillage", illustrator:"Jessi J" },
{ id:"castles", illustrator:"Julien Delval" },
{ id:"catapultrocks", illustrator:"Matthias Catrein" },
{ id:"catapult", illustrator:"Matthias Catrein" },
{ id:"rocks", illustrator:"Matthias Catrein" },
{ id:"chariotrace", illustrator:"Kurt Miller" },
{ id:"enchantress", illustrator:"Claus Stephan" },
{ id:"farmersmarket", illustrator:"Ryan Laukat" },
{ id:"gladiatorfortune", illustrator:"Kelli Stakenas" },
{ id:"gladiator", illustrator:"Kelli Stakenas" },
{ id:"fortune", illustrator:"Kelli Stakenas" },
{ id:"sacrifice", illustrator:"Joshua Stewart" },
{ id:"temple", illustrator:"Harald Lieske" },
{ id:"villa", illustrator:"Harald Lieske" },
{ id:"archive", illustrator:"Marco Morte" },
{ id:"capital", illustrator:"Marco Morte" },
{ id:"charm", illustrator:"Marco Morte" },
{ id:"crown", illustrator:"Marco Morte" },
{ id:"forum", illustrator:"Ryan Laukat" },
{ id:"groundskeeper", illustrator:"Alayna Danner" },
{ id:"legionary", illustrator:"Elisa Cella" },
{ id:"wildhunt", illustrator:"Harald Lieske" },
{ id:"triumph", illustrator:"Joshua Stewart" },
{ id:"annex", illustrator:"Joshua Stewart" },
{ id:"donate", illustrator:"Martin Hoffmann" },
{ id:"advance", illustrator:"Martin Hoffmann" },
{ id:"delve", illustrator:"Mark Poole" },
{ id:"tax", illustrator:"Raina Kuptz" },
{ id:"banquet", illustrator:"Brian Brinlee" },
{ id:"ritual", illustrator:"Joshua Stewart" },
{ id:"salttheearth", illustrator:"Raina Kuptz" },
{ id:"wedding", illustrator:"Joshua Stewart" },
{ id:"windfall", illustrator:"Joshua Stewart" },
{ id:"conquest", illustrator:"Brian Brinlee" },
{ id:"dominate", illustrator:"Martin Hoffmann" },
{ id:"aqueduct", illustrator:"Donald Crank" },
{ id:"arena", illustrator:"Martin Hoffmann" },
{ id:"banditfort", illustrator:"Julien Delval" },
{ id:"basilica", illustrator:"Claus Stephan" },
{ id:"baths", illustrator:"Lynell Ingram" },
{ id:"battlefield", illustrator:"Garret DeChellis" },
{ id:"colonnade", illustrator:"Donald Crank" },
{ id:"defiledshrine", illustrator:"Kurt Miller" },
{ id:"fountain", illustrator:"Lynell Ingram" },
{ id:"keep", illustrator:"Joshua Stewart" },
{ id:"labyrinth", illustrator:"Julien Delval" },
{ id:"mountainpass", illustrator:"Garret DeChellis" },
{ id:"museum", illustrator:"Julien Delval" },
{ id:"obelisk", illustrator:"Donald Crank" },
{ id:"orchard", illustrator:"Lynell Ingram" },
{ id:"palace", illustrator:"Mark Poole" },
{ id:"tomb", illustrator:"Martin Hoffmann" },
{ id:"tower", illustrator:"Claus Stephan" },
{ id:"triumphalarch", illustrator:"Claus Stephan" },
{ id:"wall", illustrator:"Joshua Stewart" },
{ id:"wolfden", illustrator:"Kendra Dodsworth" },
{ id:"humblecastle", illustrator:"Julien Delval" },
{ id:"crumblingcastle", illustrator:"Julien Delval" },
{ id:"smallcastle", illustrator:"Julien Delval" },
{ id:"hauntedcastle", illustrator:"Julien Delval" },
{ id:"opulentcastle", illustrator:"Julien Delval" },
{ id:"sprawlingcastle", illustrator:"Julien Delval" },
{ id:"grandcastle", illustrator:"Julien Delval" },
{ id:"kingscastle", illustrator:"Julien Delval" },
{ id:"druid", illustrator:"Grant Hansen" },
{ id:"faithfulhound", illustrator:"Lynell Ingram" },
{ id:"guardian", illustrator:"Martin Hoffmann" },
{ id:"monastery", illustrator:"Harald Lieske" },
{ id:"pixie", illustrator:"Claus Stephan" },
{ id:"tracker", illustrator:"Martin Hoffmann" },
{ id:"changeling", illustrator:"Jason Slavin" },
{ id:"fool", illustrator:"Claus Stephan" },
{ id:"ghosttown", illustrator:"Marcel-André Casasola Merkle" },
{ id:"leprechaun", illustrator:"Brian Brinlee" },
{ id:"nightwatchman", illustrator:"Elisa Cella" },
{ id:"secretcave", illustrator:"Ryan Laukat" },
{ id:"bard", illustrator:"Elisa Cella" },
{ id:"blessedvillage", illustrator:"Brian Brinlee" },
{ id:"cemetery", illustrator:"Marcel-André Casasola Merkle" },
{ id:"conclave", illustrator:"Joshua Stewart" },
{ id:"devilsworkshop", illustrator:"Claus Stephan" },
{ id:"exorcist", illustrator:"Joshua Stewart" },
{ id:"necromancer", illustrator:"Marco Morte" },
{ id:"shepherd", illustrator:"Matthias Catrein" },
{ id:"skulk", illustrator:"Elisa Cella" },
{ id:"cobbler", illustrator:"Brian Brinlee" },
{ id:"crypt", illustrator:"Lynell Ingram" },
{ id:"cursedvillage", illustrator:"Joshua Stewart" },
{ id:"denofsin", illustrator:"Mark Poole" },
{ id:"idol", illustrator:"Ryan Laukat" },
{ id:"pooka", illustrator:"Harald Lieske" },
{ id:"sacredgrove", illustrator:"Martin Hoffmann" },
{ id:"tormentor", illustrator:"Claus Stephan" },
{ id:"tragichero", illustrator:"Brian Brinlee" },
{ id:"vampire", illustrator:"Martin Hoffmann" },
{ id:"werewolf", illustrator:"Grant Hansen" },
{ id:"raider", illustrator:"Mark Poole" },
{ id:"theearthsgift", illustrator:"Julien Delval" },
{ id:"thefieldsgift", illustrator:"Julien Delval" },
{ id:"theflamesgift", illustrator:"Julien Delval" },
{ id:"theforestsgift", illustrator:"Julien Delval" },
{ id:"themoonsgift", illustrator:"Julien Delval" },
{ id:"themountainsgift", illustrator:"Julien Delval" },
{ id:"theriversgift", illustrator:"Julien Delval" },
{ id:"theseasgift", illustrator:"Julien Delval" },
{ id:"theskysgift", illustrator:"Julien Delval" },
{ id:"thesunsgift", illustrator:"Julien Delval" },
{ id:"theswampsgift", illustrator:"Julien Delval" },
{ id:"thewindsgift", illustrator:"Julien Delval" },
{ id:"hauntedmirror", illustrator:"Eric J Carter" },
{ id:"magiclamp", illustrator:"Ryan Laukat" },
{ id:"goat", illustrator:"Claus Stephan" },
{ id:"pasture", illustrator:"Matthias Catrein" },
{ id:"pouch", illustrator:"Martin Hoffmann" },
{ id:"cursedgold", illustrator:"Harald Lieske" },
{ id:"luckycoin", illustrator:"Claus Stephan" },
{ id:"willowisp", illustrator:"Julien Delval" },
{ id:"wish", illustrator:"Marcel-André Casasola Merkle" },
{ id:"bat", illustrator:"Martin Hoffmann" },
{ id:"imp", illustrator:"Claus Stephan" },
{ id:"zombieapprentice", illustrator:"Marco Morte" },
{ id:"zombiemason", illustrator:"Marco Morte" },
{ id:"zombiespy", illustrator:"Marco Morte" },
{ id:"ghost", illustrator:"Eric J Carter" },
{ id:"badomens", illustrator:"Jason Slavin" },
{ id:"delusion", illustrator:"Alayna Danner" },
{ id:"envy", illustrator:"Jason Slavin" },
{ id:"famine", illustrator:"Martin Hoffmann" },
{ id:"fear", illustrator:"Franz Vohwinkel" },
{ id:"greed", illustrator:"Claus Stephan" },
{ id:"haunting", illustrator:"Jessi J" },
{ id:"locusts", illustrator:"Brian Brinlee" },
{ id:"misery", illustrator:"Jessi J" },
{ id:"plague", illustrator:"Julien Delval" },
{ id:"poverty", illustrator:"Jessi J" },
{ id:"war", illustrator:"Julien Delval" },




{ id:"lostinthewoods", illustrator:"Claus Stephan" },
{ id:"borderguard", illustrator:"Claus Stephan" },
{ id:"ducat", illustrator:"Marco Morte" },
{ id:"lackeys", illustrator:"Grant Hansen" },
{ id:"actingtroupe", illustrator:"Julien Delval" },
{ id:"cargoship", illustrator:"Grant Hansen" },
{ id:"experiment", illustrator:"Jason Slavin" },
{ id:"improve", illustrator:"Marco Morte" },
{ id:"flagbearer", illustrator:"Grant Hansen" },
{ id:"hideout", illustrator:"Julien Delval" },
{ id:"inventor", illustrator:"Julien Delval" },
{ id:"mountainvillage", illustrator:"Harald Lieske" },
{ id:"patron", illustrator:"Claus Stephan" },
{ id:"priest", illustrator:"Julien Delval" },
{ id:"research", illustrator:"Julien Delval" },
{ id:"silkmerchant", illustrator:"Elisa Cella" },
{ id:"oldwitch", illustrator:"Jessi J" },
{ id:"recruiter", illustrator:"Julien Delval" },
{ id:"scepter", illustrator:"Marco Morte" },
{ id:"scholar", illustrator:"Elisa Cella" },
{ id:"sculptor", illustrator:"Jessi J" },
{ id:"seer", illustrator:"Joshua Stewart" },
{ id:"spices", illustrator:"Elisa Cella" },
{ id:"swashbuckler", illustrator:"Joshua Stewart" },
{ id:"treasurer", illustrator:"Claus Stephan" },
{ id:"villain", illustrator:"Jason Slavin" },
{ id:"cathedral", illustrator:"Joshua Stewart" },
{ id:"citygate", illustrator:"Harald Lieske" },
{ id:"pageant", illustrator:"Ryan Laukat" },
{ id:"sewers", illustrator:"Matthias Catrein" },
{ id:"starchart", illustrator:"Grant Hansen" },
{ id:"exploration", illustrator:"Marcel-André Casasola Merkle" },
{ id:"fair", illustrator:"Garret DeChellis" },
{ id:"silos", illustrator:"Brian Brinlee" },
{ id:"sinisterplot", illustrator:"Hans Krill" },
{ id:"academy", illustrator:"Brian Brinlee" },
{ id:"capitalism", illustrator:"Martin Hoffmann" },
{ id:"fleet", illustrator:"Martin Hoffmann" },
{ id:"guildhall", illustrator:"Hans Krill" },
{ id:"piazza", illustrator:"Martin Hoffmann" },
{ id:"roadnetwork", illustrator:"Matthias Catrein" },
{ id:"barracks", illustrator:"Martin Hoffmann" },
{ id:"croprotation", illustrator:"Brian Brinlee" },
{ id:"innovation", illustrator:"Ryan Laukat" },
{ id:"canal", illustrator:"Joshua Stewart" },
{ id:"citadel", illustrator:"Harald Lieske" },
{ id:"flag", illustrator:"Grant Hansen" },
{ id:"horn", illustrator:"Harald Lieske" },
{ id:"key", illustrator:"Claus Stephan" },
{ id:"lantern", illustrator:"Claus Stephan" },
{ id:"treasurechest", illustrator:"Joshua Stewart" },
{ id:"sauna", illustrator:"Ossi Hiekkala" },
{ id:"avanto", illustrator:"Ossi Hiekkala" },
{ id:"blackmarket", illustrator:"Franz Vohwinkel" },
{ id:"envoy", illustrator:"Matthias Catrein" },
{ id:"governor", illustrator:"Harald Lieske" },
{ id:"prince", illustrator:"Eric J Carter" },
{ id:"walledvillage", illustrator:"Doris Matthäus" },
{ id:"dismantle", illustrator:"Elisa Cella" },
{ id:"captain", illustrator:"Julien Delval" },
{ id:"church", illustrator:"Julien Delval" },
{ id:"stash", illustrator:"Martin Hoffmann" },

{ id:"summon", illustrator:"Marco Morte" },
{ id:"horse", illustrator:"Claus Stephan" },
{ id:"blackcat", illustrator:"Marco Morte" },
{ id:"sleigh", illustrator:"Marcel-André Casasola Merkle" },
{ id:"supplies", illustrator:"Grant Hansen" },
{ id:"cameltrain", illustrator:"Claus Stephan" },
{ id:"goatherd", illustrator:"Claus Stephan" },
{ id:"scrap", illustrator:"Eric J Carter" },
{ id:"sheepdog", illustrator:"Claus Stephan" },
{ id:"snowyvillage", illustrator:"Claus Stephan" },
{ id:"stockpile", illustrator:"Grant Hansen" },
{ id:"bountyhunter", illustrator:"Franz Vohwinkel" },
{ id:"cardinal", illustrator:"Claus Stephan" },
{ id:"cavalry", illustrator:"Claus Stephan" },
{ id:"groom", illustrator:"Elisa Cella" },
{ id:"hostelry", illustrator:"Elisa Cella" },
{ id:"villagegreen", illustrator:"Franz Vohwinkel" },
{ id:"barge", illustrator:"Eric J Carter" },
{ id:"coven", illustrator:"Claus Stephan" },
{ id:"displace", illustrator:"Marcel-André Casasola Merkle" },
{ id:"falconer", illustrator:"Claus Stephan" },
{ id:"fisherman", illustrator:"Marcel-André Casasola Merkle" },
{ id:"gatekeeper", illustrator:"Garret DeChellis" },
{ id:"huntinglodge", illustrator:"Claus Stephan" },
{ id:"kiln", illustrator:"Elisa Cella" },
{ id:"livery", illustrator:"Garret DeChellis" },
{ id:"mastermind", illustrator:"Franz Vohwinkel" },
{ id:"paddock", illustrator:"Elisa Cella" },
{ id:"sanctuary", illustrator:"Claus Stephan" },
{ id:"destrier", illustrator:"Garret DeChellis" },
{ id:"wayfarer", illustrator:"Garret DeChellis" },
{ id:"animalfair", illustrator:"Claus Stephan" },
{ id:"wayofthebutterfly", illustrator:"Marco Morte" },
{ id:"wayofthecamel", illustrator:"Matthias Catrein" },
{ id:"wayofthechameleon", illustrator:"Grant Hansen" },
{ id:"wayofthefrog", illustrator:"Marco Morte" },
{ id:"wayofthegoat", illustrator:"Marco Morte" },
{ id:"wayofthehorse", illustrator:"Jessi J" },
{ id:"wayofthemole", illustrator:"Jessi J" },
{ id:"wayofthemonkey", illustrator:"Marco Morte" },
{ id:"wayofthemouse", illustrator:"Marco Morte" },
{ id:"wayofthemule", illustrator:"Marco Morte" },
{ id:"wayoftheotter", illustrator:"Harald Lieske" },
{ id:"wayoftheowl", illustrator:"Marco Morte" },
{ id:"wayoftheox", illustrator:"Matthias Catrein" },
{ id:"wayofthepig", illustrator:"Marco Morte" },
{ id:"wayoftherat", illustrator:"Grant Hansen" },
{ id:"wayoftheseal", illustrator:"Marco Morte" },
{ id:"wayofthesheep", illustrator:"Hans Krill" },
{ id:"wayofthesquirrel", illustrator:"Marco Morte" },
{ id:"wayoftheturtle", illustrator:"Marco Morte" },
{ id:"wayoftheworm", illustrator:"Marco Morte" },
{ id:"delay", illustrator:"Jessi J" },
{ id:"desperation", illustrator:"Martin Hoffmann" },
{ id:"gamble", illustrator:"Martin Hoffmann" },
{ id:"pursue", illustrator:"Martin Hoffmann" },
{ id:"ride", illustrator:"Brian Brinlee" },
{ id:"toil", illustrator:"Hans Krill" },
{ id:"enhance", illustrator:"Martin Hoffmann" },
{ id:"march", illustrator:"Jessi J" },
{ id:"transport", illustrator:"Brian Brinlee" },
{ id:"banish", illustrator:"Harald Lieske" },
{ id:"bargain", illustrator:"Harald Lieske" },
{ id:"invest", illustrator:"Brian Brinlee" },
{ id:"seizetheday", illustrator:"Hans Krill" },
{ id:"commerce", illustrator:"Martin Hoffmann" },
{ id:"demand", illustrator:"Harald Lieske" },
{ id:"stampede", illustrator:"Brian Brinlee" },
{ id:"reap", illustrator:"Harald Lieske" },
{ id:"enclave", illustrator:"Brian Brinlee" },
{ id:"alliance", illustrator:"Hans Krill" },
{ id:"populate", illustrator:"Hans Krill" },

{ id:"astrolabe", illustrator:"Grant Hansen" },
{ id:"monkey", illustrator:"Grant Hansen" },
{ id:"seachart", illustrator:"Martin Hoffmann" },
{ id:"blockade", illustrator:"Claus Stephan" },
{ id:"sailor", illustrator:"Julien Delval" },
{ id:"tidepools", illustrator:"Julien Delval" },
{ id:"corsair", illustrator:"Martin Hoffmann" },
{ id:"pirate", illustrator:"Claus Stephan" },
{ id:"seawitch", illustrator:"Julien Delval" },
{ id:"anvil", illustrator:"Jessi J" },
{ id:"clerk", illustrator:"Harald Lieske" },
{ id:"investment", illustrator:"Marco Morte" },
{ id:"tiara", illustrator:"Lynell Ingram" },
{ id:"charlatan", illustrator:"Franz Vohwinkel" },
{ id:"collection", illustrator:"Franz Vohwinkel" },

{ id:"magnate", illustrator:"Harald Lieske" },
{ id:"warchest", illustrator:"Lynell Ingram" },
{ id:"trail", illustrator:"Marcel-André Casasola Merkle" },
{ id:"weaver", illustrator:"Marcel-André Casasola Merkle" },
{ id:"berserker", illustrator:"Julien Delval" },
{ id:"cauldron", illustrator:"Garret DeChellis" },
{ id:"guarddog", illustrator:"Julien Delval" },
{ id:"nomads", illustrator:"Marcel-André Casasola Merkle" },
{ id:"souk", illustrator:"Garret DeChellis" },
{ id:"wheelwright", illustrator:"Elisa Cella" },
{ id:"witchshut", illustrator:"Julien Delval" },
{ id:"bauble", illustrator:"Ryan Laukat" },
{ id:"sycophant", illustrator:"Elisa Cella" },
{ id:"townsfolk", illustrator:"Julien Delval" },
{ id:"towncrier", illustrator:"Julien Delval" },
{ id:"blacksmith", illustrator:"Julien Delval" },
{ id:"miller", illustrator:"Julien Delval" },
{ id:"elder", illustrator:"Julien Delval" },
{ id:"augurs", illustrator:"Hans Krill" },
{ id:"herbgatherer", illustrator:"Hans Krill" },
{ id:"acolyte", illustrator:"Hans Krill" },
{ id:"sorceress", illustrator:"Hans Krill" },
{ id:"sibyl", illustrator:"Hans Krill" },
{ id:"clashes", illustrator:"Harald Lieske" },
{ id:"battleplan", illustrator:"Harald Lieske" },
{ id:"archer", illustrator:"Harald Lieske" },
{ id:"warlord", illustrator:"Harald Lieske" },
{ id:"territory", illustrator:"Harald Lieske" },
{ id:"forts", illustrator:"Garret DeChellis" },
{ id:"tent", illustrator:"Garret DeChellis" },
{ id:"garrison", illustrator:"Garret DeChellis" },
{ id:"hillfort", illustrator:"Garret DeChellis" },
{ id:"stronghold", illustrator:"Garret DeChellis" },
{ id:"importer", illustrator:"Jessi J" },
{ id:"merchantcamp", illustrator:"Julien Delval" },
{ id:"odysseys", illustrator:"Julien Delval" },
{ id:"oldmap", illustrator:"Julien Delval" },
{ id:"voyage", illustrator:"Julien Delval" },
{ id:"sunkentreasure", illustrator:"Julien Delval" },
{ id:"distantshore", illustrator:"Julien Delval" },
{ id:"sentinel", illustrator:"Brian Brinlee" },
{ id:"underling", illustrator:"Claus Stephan" },
{ id:"wizards", illustrator:"Harald Lieske" },
{ id:"student", illustrator:"Harald Lieske" },
{ id:"conjurer", illustrator:"Harald Lieske" },
{ id:"sorcerer", illustrator:"Harald Lieske" },
{ id:"lich", illustrator:"Harald Lieske" },
{ id:"broker", illustrator:"Claus Stephan" },
{ id:"carpenter", illustrator:"Claus Stephan" },
{ id:"courier", illustrator:"Julien Delval" },
{ id:"innkeeper", illustrator:"Julien Delval" },
{ id:"royalgalley", illustrator:"Brian Brinlee" },
{ id:"town", illustrator:"Julien Delval" },
{ id:"barbarian", illustrator:"Julien Delval" },
{ id:"capitalcity", illustrator:"Lynell Ingram" },
{ id:"contract", illustrator:"Lynell Ingram" },
{ id:"emissary", illustrator:"Jessi J" },
{ id:"galleria", illustrator:"Claus Stephan" },
{ id:"guildmaster", illustrator:"Elisa Cella" },
{ id:"highwayman", illustrator:"Eric J Carter" },
{ id:"hunter", illustrator:"Julien Delval" },
{ id:"modify", illustrator:"Lynell Ingram" },
{ id:"skirmisher", illustrator:"Claus Stephan" },
{ id:"specialist", illustrator:"Claus Stephan" },
{ id:"swap", illustrator:"Franz Vohwinkel" },
{ id:"marquis", illustrator:"Franz Vohwinkel" },
{ id:"architectsguild", illustrator:"Martin Hoffmann" },
{ id:"bandofnomads", illustrator:"Grant Hansen" },
{ id:"cavedwellers", illustrator:"Brian Brinlee" },
{ id:"circleofwitches", illustrator:"Grant Hansen" },
{ id:"citystate", illustrator:"Marco Morte" },
{ id:"coastalhaven", illustrator:"Marco Morte" },
{ id:"craftersguild", illustrator:"Martin Hoffmann" },
{ id:"desertguides", illustrator:"Martin Hoffmann" },
{ id:"familyofinventors", illustrator:"Martin Hoffmann" },
{ id:"fellowshipofscribes", illustrator:"Eric J Carter" },
{ id:"forestdwellers", illustrator:"Brian Brinlee" },
{ id:"gangofpickpockets", illustrator:"Eric J Carter" },
{ id:"islandfolk", illustrator:"Brian Brinlee" },
{ id:"leagueofbankers", illustrator:"Martin Hoffmann" },
{ id:"leagueofshopkeepers", illustrator:"Marco Morte" },
{ id:"markettowns", illustrator:"Marco Morte" },
{ id:"mountainfolk", illustrator:"Brian Brinlee" },
{ id:"orderofastrologers", illustrator:"Brian Brinlee" },
{ id:"orderofmasons", illustrator:"Brian Brinlee" },
{ id:"peacefulcult", illustrator:"Martin Hoffmann" },
{ id:"plateaushepherds", illustrator:"Matthias Catrein" },
{ id:"trapperslodge", illustrator:"Marco Morte" },
{ id:"woodworkersguild", illustrator:"Marco Morte" },

{ id:"abundance", illustrator:"Marcel-André Casasola Merkle" },
{ id:"amphora", illustrator:"Martin Hoffmann" },
{ id:"avoid", illustrator:"Claus Stephan" },
{ id:"buriedtreasure", illustrator:"Jason Slavin" },
{ id:"bury", illustrator:"Claus Stephan" },
{ id:"cabinboy", illustrator:"Julien Delval" },
{ id:"cage", illustrator:"Jessi J" },
{ id:"cheap", illustrator:"Matthias Catrein" },
{ id:"crew", illustrator:"Julien Delval" },
{ id:"crucible", illustrator:"Claus Stephan" },
{ id:"cursed", illustrator:"Jessi J" },
{ id:"cutthroat", illustrator:"Hans Krill" },
{ id:"deliver", illustrator:"Julien Delval" },
{ id:"doubloons", illustrator:"Grant Hansen" },
{ id:"endlesschalice", illustrator:"Martin Hoffmann" },
{ id:"enlarge", illustrator:"Lorraine Schleter" },
{ id:"fated", illustrator:"Brian Brinlee" },
{ id:"fawning", illustrator:"Brian Brinlee" },
{ id:"figurehead", illustrator:"Martin Hoffmann" },
{ id:"figurine", illustrator:"Garret DeChellis" },
{ id:"firstmate", illustrator:"Julien Delval" },
{ id:"flagship", illustrator:"Hans Krill" },
{ id:"foray", illustrator:"Marco Primo" },
{ id:"fortunehunter", illustrator:"Julien Delval" },
{ id:"friendly", illustrator:"Brian Brinlee" },
{ id:"frigate", illustrator:"Claus Stephan" },
{ id:"gondola", illustrator:"Marcel-André Casasola Merkle" },
{ id:"grotto", illustrator:"Matt Jordan" },
{ id:"hammer", illustrator:"Grant Hansen" },
{ id:"harborvillage", illustrator:"Harald Lieske" },
{ id:"hasty", illustrator:"Donald Crank" },
{ id:"inherited", illustrator:"Martin Hoffmann" },
{ id:"insignia", illustrator:"Harald Lieske" },
{ id:"inspiring", illustrator:"Brian Brinlee" },
{ id:"invasion", illustrator:"Marco Primo" },
{ id:"jewelledegg", illustrator:"Marco Primo" },
{ id:"jewels", illustrator:"Garret DeChellis" },
{ id:"journey", illustrator:"Julien Delval" },
{ id:"kingscache", illustrator:"Harald Lieske" },
{ id:"landingparty", illustrator:"Harald Lieske" },
{ id:"launch", illustrator:"Marco Primo" },
{ id:"longship", illustrator:"Julien Delval" },
{ id:"looting", illustrator:"Marco Primo" },
{ id:"maelstrom", illustrator:"Julien Delval" },
{ id:"mapmaker", illustrator:"Claus Stephan" },
{ id:"maroon", illustrator:"Harald Lieske" },
{ id:"miningroad", illustrator:"Marcel-André Casasola Merkle" },
{ id:"mirror", illustrator:"Marco Primo" },
{ id:"nearby", illustrator:"Brian Brinlee" },
{ id:"orb", illustrator:"Jessi J" },
{ id:"patient", illustrator:"Donald Crank" },
{ id:"pendant", illustrator:"Martin Hoffmann" },
{ id:"peril", illustrator:"Claus Stephan" },
{ id:"pickaxe", illustrator:"Marco Primo" },
{ id:"pilgrim", illustrator:"Franz Vohwinkel" },
{ id:"pious", illustrator:"Martin Hoffmann" },
{ id:"prepare", illustrator:"Lorraine Schleter" },
{ id:"prizegoat", illustrator:"Franz Vohwinkel" },
{ id:"prosper", illustrator:"Julien Delval" },
{ id:"puzzlebox", illustrator:"Martin Hoffmann" },
{ id:"quartermaster", illustrator:"Julien Delval" },
{ id:"reckless", illustrator:"Martin Hoffmann" },
{ id:"rich", illustrator:"Brian Brinlee" },
{ id:"rope", illustrator:"Marco Primo" },
{ id:"rush", illustrator:"Marco Primo" },
{ id:"sackofloot", illustrator:"Harald Lieske" },
{ id:"scrounge", illustrator:"Claus Stephan" },
{ id:"search", illustrator:"Claus Stephan" },
{ id:"secludedshrine", illustrator:"Marcel-André Casasola Merkle" },
{ id:"sextant", illustrator:"Eric J Carter" },
{ id:"shaman", illustrator:"Marcel-André Casasola Merkle" },
{ id:"shield", illustrator:"Lynell Ingram" },
{ id:"shy", illustrator:"Jessi J" },
{ id:"silvermine", illustrator:"Martin Hoffmann" },
{ id:"siren", illustrator:"Marcel-André Casasola Merkle" },
{ id:"spellscroll", illustrator:"Elisa Cella" },
{ id:"staff", illustrator:"Elisa Cella" },
{ id:"stowaway", illustrator:"Claus Stephan" },
{ id:"swampshacks", illustrator:"Jessi J" },
{ id:"sword", illustrator:"Lynell Ingram" },
{ id:"taskmaster", illustrator:"Claus Stephan" },
{ id:"tireless", illustrator:"Martin Hoffmann" },
{ id:"tools", illustrator:"Marco Primo" },
{ id:"trickster", illustrator:"Lorraine Schleter" },
{ id:"wealthyvillage", illustrator:"Eric J Carter" },

{ id:"avanto", illustrator:"Ossi Hiekkala" },
{ id:"blackmarket", illustrator:"Franz Vohwinkel" },
{ id:"captain", illustrator:"Julien Delval" },
{ id:"church", illustrator:"Julien Delval" },
{ id:"dismantle", illustrator:"Elisa Cella" },
{ id:"envoy", illustrator:"Matthias Catrein" },
{ id:"governor", illustrator:"Harald Lieske" },
{ id:"marchland", illustrator:"Eric J. Carter" },
{ id:"prince", illustrator:"Eric J Carter" },
{ id:"sauna", illustrator:"Ossi Hiekkala" },
{ id:"saunaavanto", illustrator:"Ossi Hiekkala" },
{ id:"stash", illustrator:"Martin Hoffmann" },
{ id:"summon", illustrator:"Marco Morte" },
{ id:"walledvillage", illustrator:"Doris Matthäus" },
{ id:"princeold", illustrator:"Eric J Carter" },

{ id:"artist", illustrator:"Osamu Inoue" },
{ id:"daimyo", illustrator:"Eric J Carter" },
{ id:"mountainshrine", illustrator:"Claus Stephan" },
{ id:"fishmonger", illustrator:"Yusuke Mamada" },
{ id:"snakewitch", illustrator:"Yusuke Mamada" },
{ id:"aristocrat", illustrator:"Yusuke Mamada" },
{ id:"craftsman", illustrator:"Hasegawa" },
{ id:"riverboat", illustrator:"Elisa Cella" },
{ id:"rootcellar", illustrator:"Elisa Cella" },
{ id:"alley", illustrator:"Yusuke Mamada" },
{ id:"change", illustrator:"Julien Delval" },
{ id:"ninja", illustrator:"Elisa Cella" },
{ id:"poet", illustrator:"Yusuke Mamada" },
{ id:"rivershrine", illustrator:"Claus Stephan" },
{ id:"rusticvillage", illustrator:"Tetsu Kayama" },
{ id:"goldmine", illustrator:"Martin Hoffmann" },
{ id:"imperialenvoy", illustrator:"Eric J Carter" },
{ id:"kitsune", illustrator:"Claus Stephan" },
{ id:"litter", illustrator:"Tetsu Kayama" },
{ id:"ricebroker", illustrator:"Marco Primo" },
{ id:"ronin", illustrator:"Marco Primo" },
{ id:"tanuki", illustrator:"Hans Krill" },
{ id:"teahouse", illustrator:"Osamu Inoue" },
{ id:"samurai", illustrator:"Marco Primo" },
{ id:"rice", illustrator:"Elisa Cella" },
{ id:"continue", illustrator:"Grant Hansen" },
{ id:"amass", illustrator:"Marco Primo" },
{ id:"asceticism", illustrator:"Martin Hoffmann" },
{ id:"credit", illustrator:"Marco Primo" },
{ id:"foresight", illustrator:"Marco Primo" },
{ id:"kintsugi", illustrator:"Marco Primo" },
{ id:"practice", illustrator:"Claus Stephan" },
{ id:"seatrade", illustrator:"Marco Primo" },
{ id:"receivetribute", illustrator:"Grant Hansen" },
{ id:"gather", illustrator:"Donald Crank" },
{ id:"approachingarmy", illustrator:"Garret DeChellis" },
{ id:"bidingtime", illustrator:"Tetsu Kayama" },
{ id:"bureaucracy", illustrator:"Tetsu Kayama" },
{ id:"divinewind", illustrator:"Julien Delval" },
{ id:"enlightenment", illustrator:"Sai Beppu" },
{ id:"flourishingtrade", illustrator:"Sai Beppu" },
{ id:"goodharvest", illustrator:"Sai Beppu" },
{ id:"greatleader", illustrator:"Sai Beppu" },
{ id:"growth", illustrator:"Matthias Catrein" },
{ id:"harshwinter", illustrator:"Julien Delval" },
{ id:"kindemperor", illustrator:"Sai Beppu" },
{ id:"panic", illustrator:"Claus Stephan" },
{ id:"progress", illustrator:"Claus Stephan" },
{ id:"rapidexpansion", illustrator:"Donald Crank" },
{ id:"sickness", illustrator:"Donald Crank" },


];
