type FrenchCardTextsType = {[key: string]: string;};
export const FrenchCardTexts: FrenchCardTextsType = {}
FrenchCardTexts["BORDERVILLAGE"]= "|+1 Carte|//|+2 Actions|//---//Quand vous recevez cette carte,//recevez une carte moins ch\xE8re.";
FrenchCardTexts["FOOLSGOLD"]= "Si c'est la premi\xE8re fois que//que vous jouez un Or des Fous \xE0//ce tour, +[1]. Sinon, +[4].//---//Quand un autre joueur re\xE7oit une//Province, vous pouvez \xE9carter//cette carte de votre main, pour//recevoir un Or sur votre pioche.";
FrenchCardTexts["TRADER"]= "\xC9cartez une carte de votre main.//Recevez un Argent par [1] de son co\xFBt.//---//Lorsque vous recevez une carte,//vous pouvez d\xE9voiler cette carte//de votre main pour \xE9changer//la carte re\xE7ue contre un Argent.";
FrenchCardTexts["SILKROAD"]= "Vaut {1} pour chaque 4 cartes//Victoire que vous avez//(arrondi inf\xE9rieurement).";
FrenchCardTexts["ILLGOTTENGAINS"]= "[!1]////Vous pouvez recevoir un Cuivre en main.//---//Lorsque vous recevez cette carte, tous//vos adversaires re\xE7oivent une Mal\xE9diction.";
FrenchCardTexts["EMBASSY"]= "|+5 Cartes|//D\xE9faussez 3 cartes.////---//Lorsque vous recevez cette carte,//tous vos adversaires re\xE7oivent//un Argent.";
FrenchCardTexts["NOMADCAMP"]= "|+1 Achat|//|+[2]|//---//Cette carte est re\xE7ue sur votre//pioche (au lieu de votre d\xE9fausse).";
FrenchCardTexts["SPICEMERCHANT"]= "Vous pouvez \xE9carter une carte//Tr\xE9sor de votre main pour choisir//|+2 Cartes| et| +1 Action|;//ou| +|[2] et| +1 Achat|.";
FrenchCardTexts["ORACLE"]= "Chaque joueur (vous compris)//d\xE9voile les deux premi\xE8res cartes//de sa pioche et, selon votre choix,//les d\xE9fausse ou les replace dans//l'ordre de son choix.//Ensuite, |+2 Cartes|.";
FrenchCardTexts["CARTOGRAPHER"]= "|+1 Carte|//|+1 Action|////Consultez les 4 premi\xE8res cartes// de votre pioche. D\xE9faussez-en//autant que souhait\xE9, et replacez les//autres dans l'ordre de votre choix.";
FrenchCardTexts["NOBLEBRIGAND"]= "|+|[1]//Lorque vous achetez ou joueez cette carte//tous vos adversaires dévoilent les 2// premières cartes de leur pioche, écartent//un Argent ou un Or dévoilé que vous//choississez, défaussent le reste, et// reçoivent un Cuivre s'ils n'ont pas dévoilés//de Trésor. Vous recevez les cartes écartées.";
FrenchCardTexts["MARGRAVE"]= "|+3 Cartes|//|+1 Achat|////Tous vos adversaires piochent//une carte, puis d\xE9faussent//jusqu'\xE0 avoir 3 cartes en main.";
FrenchCardTexts["SCHEME"]= "|+1 Carte|//|+1 Action|////A ce tour, vous pouvez replacer//une carte Action sur votre pioche//quand vous la d\xE9faussez//de votre zone de jeu.";
FrenchCardTexts["INN"]= "|+2 Cartes|//|+2 Actions|////D\xE9faussez 2 cartes.//---//Lorsque vous recevez cette carte, consultez//votre d\xE9fausse, d\xE9voilez-en autant de cartes//Action que souhait\xE9 (y compris celle-ci), et//m\xE9langez-les \xE0 votre pioche.";
FrenchCardTexts["TUNNEL"]= "{!2}//---//Quand vous d\xE9faussez cette carte en//dehors de la phase Ajustement, vous//pouvez la d\xE9voiler pour recevoir un Or.";
FrenchCardTexts["CROSSROADS"]= "D\xE9voilez votre main.| +1 Carte|//par carte Victoire d\xE9voil\xE9e.//Si c'est la premi\xE8re fois que//vous jouez un Carrefour//\xE0 ce tour,| +3 Actions|.";
FrenchCardTexts["DEVELOP"]= "\xC9cartez une carte de votre main.//Recevez deux cartes sur votre//pioche, une co\xFBtant exactement//[1] de plus, et une co\xFBtant//exactement [1] de moins,//dans l'ordre de votre choix.";
FrenchCardTexts["OASIS"]= "|+1 Carte|//|+1 Action|//|+[1]|////D\xE9faussez une carte.";
FrenchCardTexts["MANDARIN"]= "|+[3]|////Placez une carte de votre main//sur votre pioche.//---//Lorsque vous recevez cette carte,//placez vos Tr\xE9sors en jeu sur votre//pioche, dans l'ordre de votre choix.";
FrenchCardTexts["CACHE"]= "[!3]//---//Quand vous recevez cette carte,//recevez deux Cuivres.";
FrenchCardTexts["DUCHESS"]= "|+[2]|//Tous les joueurs (vous inclus)//consultent la carte du haut de leur//pioche et peuvent la d\xE9fausser.//---//Si la Duchesse est dans le royaume,//vous pouvez en recevoir une//lorsque vous recevez un Duch\xE9.";
FrenchCardTexts["STABLES"]= "Vous pouvez d\xE9fausser//une carte Tr\xE9sor pour//|+3 Cartes| et| +1 Action|.";
FrenchCardTexts["JACKOFALLTRADES"]= "Recevez un Argent.//Consultez la carte du haut de votre//pioche; vous pouvez la d\xE9fausser.//Piochez jusqu'\xE0 avoir 5 cartes//en main.//Vous pouvez \xE9carter une carte//non-Tr\xE9sor de votre main.";

/* Update Pack */
FrenchCardTexts["FARMLAND"] = "//{!2}//---//Lorsque vous recevez cette carte,//\xE9cartez une carte de votre main et//recevez une carte autre//qu'une Terre Agricole co\xFBtant//exactement [2] de plus.////";
FrenchCardTexts["HAGGLER"] = "|+[2]|//---//\xC0 ce tour, quand vous recevez//une carte que vous avez achet\xE9e,//recevez une carte//non-Victoire moins ch\xE8re.";
FrenchCardTexts["HIGHWAY"] = "|+1 Carte|//|+1 Action|//---//\xC0 ce tour, les cartes//co\xFBtent [1] de moins.";
FrenchCardTexts["BERSERKER"] = "Recevez une carte coûtant//moins que celle-ci.//Tous vos adversaires défaussent//jusqu'à avoir 3 cartes en main.//---//Quand vous recevez cette carte,//jouez-la si vous avez//une carte Action en jeu.";
FrenchCardTexts["GUARDDOG"] = "|+2 Cartes|//Si vous avez en main 5 cartes//ou moins, |+2 Cartes|.//---//Quand un autre joueur joue une//Attaque, vous pouvez d'abord jouer//cette carte depuis votre main.";
FrenchCardTexts["NOMADS"] = "|+1 Achat|//|+[2]|//---//Quand vous recevez ou//écartez cette carte, +[2].";
FrenchCardTexts["TRAIL"] = "|+1 Carte|//|+1 Action|//---//Quand vous recevez, écartez,//ou défaussez cette carte en//dehors de la phase Ajustement,//vous pouvez la jouer.";
FrenchCardTexts["WEAVER"] = "Recevez deux Argents ou//une carte coûtant jusqu'à [4].//---//Quand vous défaussez cette carte//en dehors de la phase Ajustement,//vous pouvez la jouer.";
FrenchCardTexts["SOUK"] = "|+1 Achat|//|+[7]|//-[1] par carte en main. (Vous ne pouvez//pas aller en-dessous de [0].)//---//Quand vous recevez cette carte, écartez//jusqu'à 2 cartes de votre main.";
FrenchCardTexts["CAULDRON"] = "////|[!2]|//|+1 Achat|//La troisième fois que vous//recevez une Action à ce tour,//tous vos adversaires//reçoivent une Malédiction.////";
FrenchCardTexts["WHEELWRIGHT"] = "|+1 Carte|//|+1 Action|//Vous pouvez défausser une carte//pour recevoir une Action//coûtant autant ou moins.";
FrenchCardTexts["WITCHSHUT"] = "|+4 Cartes|//Défaussez 2 cartes, dévoilées.//Si les deux sont des Actions,//tous vos adversaires//reçoivent une Malédiction.";
