type FrenchCardTextsType = {[key: string]: string;};
export const FrenchCardTexts: FrenchCardTextsType = {}
  FrenchCardTexts["CAGE"]= "Mettez de côté jusqu'à//4 cartes de votre main//face cachée (sous cette carte).//La prochaine fois que vous//recevez une carte Victoire,//écartez cette carte et prenez//en main les cartes mises de côté//à la fin de votre tour.";
  FrenchCardTexts["GROTTO"]= "|+1 Action|////Mettez de côté jusqu'à//4 cartes de votre main//face cachée (sous cette carte).//Au début de votre//prochain tour, défaussez-les,//puis piochez-en autant.";
  FrenchCardTexts["JEWELLEDEGG"]= "[!1]//|+1 Achat|//---//Quand vous écartez cette//carte, recevez un Trophée.";
  FrenchCardTexts["SEARCH"]= "|+[2]|////La prochaine fois qu'une//pile de la Réserve devient vide,//écartez cette carte et//recevez un Trophée.";
  FrenchCardTexts["SHAMAN"]= "|+1 Action|//|+[1]|////Vous pouvez écarter//une carte de votre main.//---//Dans les parties utilisant//cette carte, au début de//votre tour, recevez une carte//du rebut coûtant jusqu'à [6].";
  FrenchCardTexts["SECLUDEDSHRINE"]= "|+[1]|////La prochaine fois que vous//recevez un Trésor, écartez//jusqu'à 2 cartes de votre main.";
  FrenchCardTexts["SIREN"]= "Tous vos adversaires//reçoivent une Malédiction.////Au début de votre prochain tour, piochez//jusqu'à avoir 8 cartes en main.//---//Quand vous recevez cette carte,//écartez-la à moins d'écarter une//Action de votre main.";
  FrenchCardTexts["STOWAWAY"]= "Au début de votre//prochain tour, |+2 Cartes|.//---//Quand un joueur reçoit//une carte Durée, vous//pouvez jouer cette carte//de votre main.";
  FrenchCardTexts["TASKMASTER"]= "|+1 Action|, |+|[1], et si à ce tour//vous recevez une carte//coûtant exactement [5],//répétez cette capacité//au début de votre prochain tour.";
  FrenchCardTexts["ABUNDANCE"]= "La prochaine fois que vous//recevez une carte Action,//|+1 Achat| et |+|[3].";
  FrenchCardTexts["CABINBOY"]= "|+1 Carte|//|+1 Action|////Au début de votre prochain tour,//choisissez: |+|[2];//ou écartez cette carte pour//recevoir une carte Durée.";
  FrenchCardTexts["CRUCIBLE"]= "Écartez une carte//de votre main.//|+|[1] par [1] de son coût.";
  FrenchCardTexts["FLAGSHIP"]= "|+[2]|////La prochaine fois que//vous jouez une carte Action//non-Ordre, rejouez-la.";
  FrenchCardTexts["FORTUNEHUNTER"]= "|+[2]|////Consultez les 3 premières//cartes de votre pioche.//Vous pouvez en jouer//un Trésor. Replacez les//autres dans l’ordre//de votre choix.";
  FrenchCardTexts["GONDOLA"]= "Maintenant ou au début//de votre prochain tour: |+|[2].//---//Quand vous recevez cette carte,//vous pouvez jouer//une carte Action de votre main.";
  
  FrenchCardTexts["HARBORVILLAGE"]= "|+1 Carte|//|+2 Actions|////Après la prochaine Action//que vous jouez à ce tour//si elle vous a donné//|+|[], |+|[1]."; //TODO
  FrenchCardTexts["LANDINGPARTY"]= "|+2 Cartes|//|+2 Actions|////La prochaine fois que la première carte//que vous jouez à un tour est un Trésor,//placez ensuite cette carte sur votre pioche."; // TODO
  
  FrenchCardTexts["MAPMAKER"]= "Consultez les 4 premières cartes//de votre pioche. Prenez-en 2 en main//et défaussez les autres.//---//Quand un joueur reçoit//une carte Victoire, vous pouvez//jouez cette carte de votre main.";
  FrenchCardTexts["MAROON"]= "Écartez une carte de votre main.//|+2 Cartes| pour chacun de ses types.//(Action, Attaque, etc.).";
  FrenchCardTexts["ROPE"]= "[!1]//|+1 Achat|////Au début de votre prochain tour,//|+1 Carte| et vous pouvez écarter//une carte de votre main.";
  FrenchCardTexts["SWAMPSHACKS"]= "|+2 Actions|////|+1 Carte| pour chaque 3 cartes que//vous avez dans votre zone de jeu//(arrondi à l'unité inférieure).";
  
  FrenchCardTexts["TOOLS"]= "Recevez un exemplaire d'une carte//qu'un joueur a en jeu."; //TODO
  
  FrenchCardTexts["BURIEDTREASURE"]= "Au début de votre prochain tour,//|+1 Achat| et |+|[3].//---//Lorsque vous recevez cette carte,//jouez-la.";
  FrenchCardTexts["CREW"]= "|+3 Cartes|////Au début de votre prochain tour,//replacez cette carte sur votre pioche.";
  FrenchCardTexts["CUTTHROAT"]= "Tous vos adversaires défaussent//jusqu'à avoir 3 cartes en main.//La prochaine fois qu'un joueur//reçoit un Trésor coûtant//[5] ou plus, recevez un Trophée.";
  FrenchCardTexts["ENLARGE"]= "Maintenant et au début de votre//prochain tour: Écartez une carte//de votre main, et recevez une carte//coûtant jusqu'à [2] de plus.";
  FrenchCardTexts["FIGURINE"]= "|+2 Cartes|////Vous pouvez défausser//une carte Action pour//|+1 Achat| et |+|[1].";
  FrenchCardTexts["FIRSTMATE"]= "Jouez autant que souhaité//des cartes Action de même nom//de votre main, puis pioche//jusqu'à avoir 6 cartes en main."; // REVIEW
  FrenchCardTexts["FRIGATE"]= "|+[3]|////Jusqu'au début de votre prochain//tour, quand un adversaire joue une//carte Action, il défausse jusqu'à avoir//4 cartes en main par la suite."; // REVIEW
  FrenchCardTexts["LONGSHIP"]= "|+2 Actions|////Au début de votre prochain//tour, |+2 Cartes|.";
  FrenchCardTexts["MININGROAD"]= "|+1 Action|//|+1 Achat|//|+[2]|////Une fois ce tour, lorsque vous recevez//un Trésor, vous pouvez le jouer.";
  FrenchCardTexts["PENDANT"]= "|+|[1] par Trésor//de nom différent//que vous avez en jeu.";
  FrenchCardTexts["PICKAXE"]= "[!1]////Écartez une carte de votre main.//Si elle coûte [3] ou plus,//recevez en main un Trophée.";
  FrenchCardTexts["PILGRIM"]= "|+4 Cartes|////Placez une carte de votre main//sur votre pioche.";
  FrenchCardTexts["QUARTERMASTER"]= "Au début de chacun vos tour,//pour la suite de la partie, choisissez ://recevez et mettez de côté ici//une carte coûtant jusqu'à [4];//ou prenez en main une carte//mise ici de côté.";
  FrenchCardTexts["SILVERMINE"]= "Recevez en main un Trésor//coûtant moins que cette carte.";
  FrenchCardTexts["TRICKSTER"]= "Tous vos adversaires//reçoivent une Malédiction.//Une fois à ce tour,//quand vous défaussez un Trésor//de votre zone de jeu,//vous pouvez le mettre de côté.//Prenez-le en main à la fin du tour.";
  FrenchCardTexts["WEALTHYVILLAGE"]= "|+1 Carte|//|+2 Actions|//---//Quand vous recevez cette carte,//si vous avez en jeu au moins//3 Trésors de noms différents,//recevez un Trophée.";
  FrenchCardTexts["SACKOFLOOT"]= "[!1]//|+1 Achat|//Recevez un Trophée.";
  FrenchCardTexts["KINGSCACHE"]= "Vous pouvez jouer un trésor//depuis votre main 3 fois.";
  FrenchCardTexts["DOUBLOONS"]= "[!3]////---//Quand vous recevez cette carte,//recevez un Or.";
  FrenchCardTexts["ENDLESSCHALICE"]= "Maintenant et au début de tous//vos tours pour la suite de la partie ://[!1]//|+1 Achat|";
  FrenchCardTexts["FIGUREHEAD"]= "[!3]////Au début de votre//prochain tour, |+2 Cartes|.";
  FrenchCardTexts["HAMMER"]= "[!3]////Recevez une carte coûtant//jusqu'à [4].";
  FrenchCardTexts["INSIGNIA"]= "[!3]////À ce tour, quand vous//recevez une carte, vous pouvez//la placer sur votre pioche.";
  FrenchCardTexts["JEWELS"]= "[!3]//|+1 Achat|////Au début de votre prochain//tour, placez cette carte//en-dessous de votre pioche.";
  FrenchCardTexts["ORB"]= "Consultez votre défausse. Choisissez ://jouez-en une carte Action ou Trésor,////ou |+1 Achat| et |+|[3].";
  FrenchCardTexts["PRIZEGOAT"]= "[!3]//|+1 Achat|////Vous pouvez écarter//une carte de votre main.";
  FrenchCardTexts["PUZZLEBOX"]= "[!3]//|+1 Achat|////Vous pouvez mettre de côté//une carte de cotre main face cachée.//Prenez-la en main//à la fin du tour.";
  FrenchCardTexts["SEXTANT"]= "[!3]//|+1 Achat|////Consultez les 5 cartes du haut//de votre pioche. Défaussez-en autant//que souhaité, et replacez le reste//dans l'ordre de votre choix.";
  FrenchCardTexts["SHIELD"]= "[!3]//|+1 Achat|//---//Quand un adversaire joue une Attaque,//vous pouvez d'abord révéler//cette carte de votre main//pour ne pas être affecté.";
  FrenchCardTexts["SPELLSCROLL"]= "Écartez cette carte pour//recevoir une carte moins chère.//Si c'est une Action ou un Trésor,//vous pouvez la jouer.";
  FrenchCardTexts["STAFF"]= "[!3]//|+1 Achat|////Vous pouvez jouer une carte Action//depuis votre main.";
  FrenchCardTexts["SWORD"]= "[!3]//|+1 Achat|////Tous vos adversaires défaussent//jusqu'à avoir 4 cartes en main.";
  



FrenchCardTexts["BURY"]= "|+1 Achat|////Placez n'importe quelle carte de votre défausse//en-dessous de votre pioche.";
FrenchCardTexts["AVOID"]= "|+1 Achat|////La prochaine fois que vous mélangez à ce tour,//choisissez jusqu'à 3 cartes à placer dans votre défausse.";
FrenchCardTexts["DELIVER"]= "|+1 Achat|////À ce tour, chaque fois que vous recevez une carte,//mettez-la de côté et prenez-la en main à la fin du tour.";
FrenchCardTexts["PERIL"]= "Vous pouvez écarter une carte Action de votre main//pour recevoir un Trophée.";
FrenchCardTexts["RUSH"]= "|+1 Achat|////La prochaine vous que vous recevez//une carte Action à ce tour, jouez-la.";
FrenchCardTexts["FORAY"]= "Défaussez 3 cartez, en les dévoilant. Si elles ont// 3 noms différents, recevez un Trophée.";
FrenchCardTexts["LAUNCH"]= "Une fois par tour : retournez à votre phase Action.//|+1 Carte|, |+1 Action|, et |+1 Achat|.";
FrenchCardTexts["MIRROR"]= "|+1 Achat|////La prochaine fois que vous recevez une carte Action à ce tour,//recevez-en un exemplaire.";
FrenchCardTexts["PREPARE"]= "Mettez de côté votre main face visible. Au début de//votre prochain tour, jouez les Actions et Trésors//dans l'ordre de votre choix, puis défaussez le reste.";
FrenchCardTexts["SCROUNGE"]= "Choisissez : écartez une carte de votre main;//ou recevez un Domaine depuis le rebut, et dans ce cas,//recevez une carte coûtant jusqu'à [5].";
FrenchCardTexts["JOURNEY"]= "Ne défaussez pas les cartes en jeu en phase d'Ajustement à ce tour.//Jouez un tour supplémentaire après celui-ci//(mais pas un troisième consécutif).";
FrenchCardTexts["MAELSTROM"]= "Écartez 3 cartes de votre main. Tous vos adversaires//ayant en main 5 cartes ou plus en écartent une.";
FrenchCardTexts["LOOTING"]= "Recevez un Trophée.";
FrenchCardTexts["INVASION"]= "Vous pouvez jouer une Attaque depuis votre main. Recevez un Duché.//Recevez une Action sur votre pioche. Recevez un Trophée; jouez-le.";
FrenchCardTexts["PROSPER"]= "Recevez un Trophée, ainsi que n'importe quel nombre//de Trésors de noms différents.";
FrenchCardTexts["CHEAP"]= "Les cartes Abordables coûtent [1] de moins.";
FrenchCardTexts["CURSED"]= "Quand vous recevez une carte Maudite,//recevez un Trophée et une Malédiction.";
FrenchCardTexts["FATED"]= "Quand vous mélangez, vous pouvez consulter les cartes et dévoiler//des cartes Destinées pour les placer en haut ou en bas.";
FrenchCardTexts["FAWNING"]= "Quand vous recevez une Province,//recevez une carte Servile.";
FrenchCardTexts["FRIENDLY"]= "Au début de votre phase Ajustement//vous pouvez défausser une carte Amicale//pour recevoir une carte Amicale.";
FrenchCardTexts["HASTY"]= "Quand vous recevez une carte Impatiente,//mettez-la de côté et jouez-la//au début de votre prochain tour.";
FrenchCardTexts["INHERITED"]= "Mise en place : vous commencez la partie avec une carte Héritée//à la place d'une carte de départ de votre choix.";
FrenchCardTexts["INSPIRING"]= "Après avoir joué une carte Exaltante à votre tour,//vous pouvez jouer depuis votre main une Action//dont vous n'avez pas d'exemplaire en jeu.";
FrenchCardTexts["NEARBY"]= "Quand vous recevez une carte Proche, |+1 Achat|.";
FrenchCardTexts["PATIENT"]= "Au début de votre phase Ajustement, vous pouvez//mettre de côté des cartes Patientes depuis votre main//pour les jouer au début de votre prochain tour.";
FrenchCardTexts["PIOUS"]= "Quand vous recevez une carte Pieuse, vous pouvez//écarter une carte de votre main.";
FrenchCardTexts["RECKLESS"]= "Suivez les instructions des cartes Téméraires jouées deux fois.//Quand vous en défaussez une de votre zone de jeu,//replacez-la dans sa pile.";
FrenchCardTexts["RICH"]= "Quand vous recevez une carte Riche, recevez un Argent.";
FrenchCardTexts["SHY"]= "Au début de votre tour, vous pouvez défausser//une carte Timide pour |+2 Cartes|.";
FrenchCardTexts["TIRELESS"]= "Quand vous défaussez une carte Infatigable//de votre zone de jeu, mettez-la de côté//et placez-la sur votre pioche à la fin de votre tour.";